name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest nightly with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  lint:
    name: Clippy check
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install latest nightly with clippy
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: clippy

      - name: Run cargo clippy without features
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --no-default-features -- -D warnings

      - name: Run cargo clippy with default features
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets -- -D warnings

      - name: Run cargo clippy with all features
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings

  build_and_test:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        rust: [ stable, nightly, 1.46.0 ]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Run cargo build without features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features

      - name: Run cargo test without features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features

      - name: Run cargo build with default features
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Run cargo test with default features
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run cargo build with all features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features

      - name: Run cargo test with all features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
